### ISSUE TITLE
Can't archive certain channels

### ISSUE THREAD

**Issue by tlontravis** [robkorn/urbit-operator-toolkit#3]
This is a great tool, and I was able to archive some notebooks and channels.

but if I try to do this on:
/~landscape/ship/~bitbet-bolbel/urbit-community/resource/chat/ship/~nibset-napwyn/grants--bounties--projects-1653

`./urbit-content-archiver chat  ~nibset-napwyn grants--bounties--projects-1653`

It seems like it makes an attempt (I can see the http request in my dojo) but it stops after a few seconds:

    Requesting ~nibset-napwyn/grants--bounties--projects-1653 chat graph from your ship...
    Failed to export chat. Please make sure that the `ship` & `name` are valid and are from a chat that your ship has joined.

Same thing happens when `./urbit-content-archiver chat ~darrux-landes general`

Hope you can help with this! You can message me at ~lorfeb-taglut as well.

**Comment by robkorn** [comment]
Ah I updated the Rust airlock a week or so ago to properly deal with deleted message parsing properly, and this project was not using a specific version as a dependency, but was using the git branch, and so if you didn't explicitly run `cargo update` after I updated the Rust airlock then it would still be broken.

Suffice to say, I've updated this project with the strict version dependency to the Rust airlock version that is most updated/currently works, so simply `git pull` and rerun the setup script and you should be good to go. I tested the command you provided and it works.

I've also now added some printing if node parsing ever fails so in the future it'll be easier to report the failure case if graph-store updates node contents in some sort of breaking change.
